name: Build

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    types: [ opened, synchronize, reopened ]
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: corretto
        java-version: 18
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute Gradle build
      run: ./gradlew build
